- name: Install Accounts Service Utilites
  hosts: webservers
  remote_user: deploy
  become: true
  roles:     
    - nginx
    - certbot
    - ruby
    - rails
    - parity
    - monit
    - ANXS.postgresql
    - geerlingguy.nodejs


